package com.kissaki

object Log extends Enumeration {
	//log
	type Log = Value
	val LOG_TYPE_INITIALIZED,
	LOG_TYPE_CALLPARENT,LOG_TYPE_CALLED_AS_PARENT,
	
	LOG_TYPE_CALLCHILD,LOG_TYPE_CALLED_AS_CHILD,
	
	LOG_TYPE_CALLMYSELF,LOG_TYPE_CALLED_MYSELF,
	
	LOG_TYPE_INPUT_TO_PARENTCANDIDATE,
	LOG_TYPE_PARENTCANDIDATE_RECEIVED,
	LOG_TYPE_PARENTCANDIDATE_ANSWERED,
	LOG_TYPE_CHILD_RECEIVED,
	LOG_TYPE_PARENT_CHILD_CONNECTED = Value
}